# Generated by Django 4.2.6 on 2023-10-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3_manager', '0002_playtime_track_fix_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='fix_track',
        ),
        migrations.AddField(
            model_name='track',
            name='solo',
            field=models.BooleanField(default=False),
        ),
    ]
