# Generated by Django 4.2.6 on 2023-10-23 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3_manager', '0004_remove_playtime_seconds_playtime_playtime_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='playtime',
            name='play_full_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='override_playtime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='playtime_seconds',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(600)]),
        ),
    ]
