# Generated by Django 4.2.6 on 2023-10-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3_manager', '0007_track_mp3_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='playtime',
            name='play_whole_playlist',
            field=models.BooleanField(default=False),
        ),
    ]
