# Generated by Django 4.2.6 on 2023-10-30 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mp3_manager', '0009_playlist_track_playlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='playtime',
            name='playlist_selection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mp3_manager.playlist'),
        ),
    ]
