# Generated by Django 4.2.6 on 2023-11-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3_manager', '0010_playtime_playlist_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='playtime',
            name='lights_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playtime',
            name='music_only',
            field=models.BooleanField(default=False),
        ),
    ]
