# Generated by Django 4.2.6 on 2023-11-18 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3_manager', '0011_playtime_lights_only_playtime_music_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='127.0.0.0', max_length=200)),
                ('user_id', models.CharField(blank=True, default='XXXX', max_length=200, null=True)),
                ('name_stub', models.CharField(blank=True, default='party', max_length=200, null=True)),
                ('brightness', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('primary_R', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(254)])),
                ('primary_G', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(254)])),
                ('primary_B', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(254)])),
                ('secondary_R', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(254)])),
                ('secondary_G', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(254)])),
                ('secondary_B', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(254)])),
                ('primary_colour', models.BooleanField(default=False)),
                ('fade', models.BooleanField(default=False)),
                ('random_colour', models.BooleanField(default=False)),
                ('random_interval', models.BooleanField(default=False)),
                ('interval_size', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(254)])),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='bpm',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)]),
        ),
    ]
