# Generated by Django 4.2.6 on 2023-11-18 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3_manager', '0012_bridge_light_track_bpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='primary_H',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='light',
            name='primary_S',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(254)]),
        ),
        migrations.AddField(
            model_name='light',
            name='primary_V',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(254)]),
        ),
        migrations.AddField(
            model_name='light',
            name='secondary_H',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='light',
            name='secondary_S',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(254)]),
        ),
        migrations.AddField(
            model_name='light',
            name='secondary_V',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(254)]),
        ),
    ]
