# Generated by Django 4.2.6 on 2023-11-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3_manager', '0013_light_primary_h_light_primary_s_light_primary_v_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='alternate_colour',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='light',
            name='primary_colour',
            field=models.BooleanField(default=True),
        ),
    ]
