# Generated by Django 4.2.6 on 2023-11-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3_manager', '0014_light_alternate_colour_alter_light_primary_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridge',
            name='room',
            field=models.CharField(blank=True, default='party', max_length=200, null=True),
        ),
    ]
