# Generated by Django 4.2.6 on 2023-11-26 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3_manager', '0015_bridge_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='hue_bridge_id',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(254)]),
        ),
    ]
