# Generated by Django 4.2.6 on 2023-11-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3_manager', '0016_light_hue_bridge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playtime',
            name='ghost',
            field=models.BooleanField(default=False),
        ),
    ]
