# Generated by Django 4.2.6 on 2023-12-23 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3_manager', '0018_playtime_pause_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('pin_id', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)])),
                ('light_on', models.BooleanField(default=True)),
            ],
        ),
    ]
