# Generated by Django 4.2.6 on 2023-12-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3_manager', '0020_light_brightness_light_override_brightness'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='randomise_brightness',
            field=models.BooleanField(default=False),
        ),
    ]
