# Generated by Django 4.2.6 on 2024-02-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3_manager', '0021_light_randomise_brightness'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='off',
            field=models.BooleanField(default=False),
        ),
    ]
